CREATE TABLE IF NOT EXISTS application
(
    id         			integer GENERATED BY DEFAULT AS identity,
	uuid    			text 					 NOT NULL,
    name				text 					 NOT NULL,
	description			text,
    master_secret		text 					 NOT NULL,
    api_key				text 					 NOT NULL,
    logo				text,
	
    active     			boolean		DEFAULT true NOT NULL,
    
    -- Auditing fields
    created_at 			timestamptz          	 NOT NULL DEFAULT NOW(),
    created_by 			text                  	 NOT NULL DEFAULT 'NA',
    updated_at 			timestamptz          	 NOT NULL DEFAULT NOW(),
    updated_by 			text                 	 NOT NULL DEFAULT 'NA',
    version    			integer              	 NOT NULL DEFAULT 0,

    CONSTRAINT application_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS variant
(
    id         				integer GENERATED BY DEFAULT AS identity,
	uuid    				text 					 NOT NULL,
    application_id			integer                  NOT NULL,
    name					text 					 NOT NULL,
    description				text,
	type    				text 					 NOT NULL,
    secret      			text 					 NOT NULL,
    api_key					text 					 NOT NULL,
    config              	jsonb                    NOT NULL,
    config_file				bytea,
    config_file_checksum	numeric,
	
    active     				boolean		DEFAULT true NOT NULL,
    
    -- Auditing fields
    created_at 			timestamptz          	 NOT NULL DEFAULT NOW(),
    created_by 			text                  	 NOT NULL DEFAULT 'NA',
    updated_at 			timestamptz          	 NOT NULL DEFAULT NOW(),
    updated_by 			text                 	 NOT NULL DEFAULT 'NA',
    version    			integer              	 NOT NULL DEFAULT 0,

    CONSTRAINT variant_pkey PRIMARY KEY (id),
    CONSTRAINT variant_application_id_fkey FOREIGN KEY (application_id) REFERENCES application (id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS topic
(
    id         			integer GENERATED BY DEFAULT AS identity,
	uuid    			text 					 NOT NULL,
    name				text 					 NOT NULL,
	
    active     			boolean		DEFAULT true NOT NULL,
    
    -- Auditing fields
    created_at 			timestamptz          	 NOT NULL DEFAULT NOW(),
    created_by 			text                  	 NOT NULL DEFAULT 'NA',
    updated_at 			timestamptz          	 NOT NULL DEFAULT NOW(),
    updated_by 			text                 	 NOT NULL DEFAULT 'NA',
    version    			integer              	 NOT NULL DEFAULT 0,

    CONSTRAINT topic_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS installation
(
    id         			integer GENERATED BY DEFAULT AS identity,
	uuid    			text 					 NOT NULL,
    alias				text,
    device_token		text 					 NOT NULL,
    device_type 		text 					 NOT NULL,
    operating_system	text 					 NOT NULL,
    os_version      	text 					 NOT NULL,
    platform          	text 					 NOT NULL,
    variant_id         	integer 					 NOT NULL,
	
    active     			boolean		DEFAULT true NOT NULL,
    
    -- Auditing fields
    created_at 			timestamptz          	 NOT NULL DEFAULT NOW(),
    created_by 			text                  	 NOT NULL DEFAULT 'NA',
    updated_at 			timestamptz          	 NOT NULL DEFAULT NOW(),
    updated_by 			text                 	 NOT NULL DEFAULT 'NA',
    version    			integer              	 NOT NULL DEFAULT 0,

    CONSTRAINT installation_pkey PRIMARY KEY (id),
    CONSTRAINT installation_uq UNIQUE (variant_id, device_token),
    CONSTRAINT installation_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES variant (id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS installation_topic
(
    installation_id    	integer 					 NOT NULL,
    topic_id        	integer 					 NOT NULL,
	
    -- Auditing fields
    created_at 			timestamptz          	 NOT NULL DEFAULT NOW(),
    created_by 			text                  	 NOT NULL DEFAULT 'NA',
    updated_at 			timestamptz          	 NOT NULL DEFAULT NOW(),
    updated_by 			text                 	 NOT NULL DEFAULT 'NA',
    version    			integer              	 NOT NULL DEFAULT 0,

    CONSTRAINT installation_topic_pkey PRIMARY KEY (installation_id, topic_id),
    CONSTRAINT installation_topic_installation_id_fkey FOREIGN KEY (installation_id) REFERENCES installation (id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT installation_topic_topic_id_fkey FOREIGN KEY (topic_id) REFERENCES topic (id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS push_message
(
    id         			integer GENERATED BY DEFAULT AS identity,
    application_id		integer                  NOT NULL,
	message    			jsonb 					 NOT NULL,
    ip_address     		text 					 NOT NULL,
    client_identifier	text 					 NOT NULL,
    open_counter       	integer,
	first_open_at		timestamptz,
    last_open_at		timestamptz,

    -- Auditing fields
    created_at 			timestamptz          	 NOT NULL DEFAULT NOW(),
    created_by 			text                  	 NOT NULL DEFAULT 'NA',
    updated_at 			timestamptz          	 NOT NULL DEFAULT NOW(),
    updated_by 			text                 	 NOT NULL DEFAULT 'NA',
    version    			integer              	 NOT NULL DEFAULT 0,

    CONSTRAINT push_message_pkey PRIMARY KEY (id),
    CONSTRAINT push_message_application_id_fkey FOREIGN KEY (application_id) REFERENCES application (id) ON UPDATE NO ACTION ON DELETE NO ACTION
);